on:
  push:
    branches: ['master']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: Run code typecheck
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker images
        run: docker build -t typecheck .

      - name: Run typecheck
        run: docker run typecheck

  portainer_update:
    name: Portainer stack update
    runs-on: ubuntu-latest
    needs: [typecheck]
    steps:
      - uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.PORTAINER_WEBHOOK_URL }}
          timeout: 600 # 10m - Webhook doesn't respond until deployment is done (it can take a few minutes)
